### ISSUE TITLE
hetzner.cloud

### ISSUE THREAD

**Issue by marketarea** [WietseWind/docker-rippled-validator#1]
How i can setup the validator to hetzner.cloud ?

**Comment by WietseWind** [comment]
Yeah that's possible. Let's say you create a host running Ubuntu 16.04, you can first install Docker-CE (Community Edition, open source):
https://docs.docker.com/install/linux/docker-ce/ubuntu/

Then you can just follow my tutorial just like any DigitalOcean customer would do;
https://medium.com/@WietseWind/how-to-run-a-ripple-validator-digitalocean-7e5fca1c3d77

**Comment by marketarea** [comment]
Thanks a lot!

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10
