### ISSUE TITLE
Can I run this with Docker Compose?

### ISSUE THREAD

**Issue by kimhoegcit** [WietseWind/docker-rippled-validator#9]
Looked at the Go scripts, seems like you are passing some params to the Docker, I am wondering if Docker Compose does the job. 

I have created a container by pulling the Docker hub image using Docker Compose, I noticed that my ledger is empty every time I start the container and it will take time to resync the ledger.

**Comment by WietseWind** [comment]
It will indeed take (a lot of) time to re-sync. If you want the node to be able to sync faster, you will have to allow the container to persist state. It doesn't matter if you use compose or not here, you'll have to map the data store directory from persistent storage to the storage directory inside the container.

**Comment by kimhoegcit** [comment]
Hi

Do I need to sync if I set it to private ledger? or how do I initialize a new ledger?

Thanks!

**Comment by WietseWind** [comment]
By changing the network and peers in the config, and starting with a clean database. The docker container is running stock rippled. Please see the docs on xrpl.org for more information.
